### PR TITLE
close connection after transaction

### PR DESCRIPTION
**Pull request by randreucetti**
#406

### CODE REVIEW

**Comment by marcospereira** [comment]
Thank you very much, @randreucetti. 

I saw that the build [is breaking here](https://travis-ci.org/playframework/play-slick/jobs/248833741#L1794-L1801), but it is not related to your change. Instead, it is the same problem we had [with this sample project](https://github.com/playframework/play-java-ebean-example/pull/45).

I'm already preparing a fix so that we can move your PR forward.

**Comment by marcospereira** [comment]
@randreucetti see #408.

Could you please rebase against the master branch?

Thanks.

**Comment by randreucetti** [comment]
Rebase done!

**Comment by marcospereira** [comment]
Thank you @randreucetti. And sorry for the long time to move this forward.

**Comment by marcospereira** [comment]
Backport to 3.0.x: 0b1ed72

**Pull request merged**
