### PR TITLE
Upgrade Slick to 3.0.2

### PR DESCRIPTION
**Pull request by nremond**

### CODE REVIEW

**Comment by dotta** [comment]
Thanks Nicolas. I'm happy to merge this, but note I don't plan to release play-slick for slick 3.0.2, since you can just bump the slick version in your build and keep using play-slick 1.0.1.

**Comment by nremond** [comment]
Good to know. As I'm interested by this upgrade, I'll do that.

**Comment by dotta** [comment]
After some more thinking, now I'm of the idea we shouldn't merge this PR.

I can definitely see the why it's desirable to bump the Slick version. However, the downside it that users cannot use a Slick version that is smaller than the one included by play-slick. This because Slick minor releases are only guaranteed to be *backward* binary compatible, and are not (also) forward binary compatible. (@szeiger could you confirm my understanding is correct.)

play-slick 1.0.1 was built with Slick 3.0.1 because of https://github.com/playframework/play-slick/issues/266 (see also https://github.com/slick/slick/pull/1152) and https://github.com/slick/slick/commit/3da8321348b990cc012beb446687b03e395c677e. But I'd say that if we don't have a really good reason for bumping the Slick version, then we shouldn't do it for a trailing point release.

**Comment by szeiger** [comment]
There's no backward binary compatibility guarantee, so you'd have to verify that play-slick works with all version that you want to support but could still declare the latest one as the default. At least that's my understanding of the kind of compatibility we check with MiMa. The only way to break backwards compatibility is by adding new features, so if you *can* still build against an older version, that version should be OK, no matter which newer version you actually build against.

**Comment by dotta** [comment]
@szeiger s/backward/forward :-)

Other than that, since I don't feel like manually validating each release, my thinking is still that we should bump the Slick version in a play-slick trailing point release only if there is a compelling reason for doing so.

Therefore, I'm closing this PR. @nremond I hope you don't mind, and I'm of course open to discussion if you disagree.

**Comment by nremond** [comment]
Of course not ! I fully understand.

**Comment by dotta** [comment]
Sounds good. Thanks Nicolas!

**Pull request closed without merging**
