### PR TITLE
bump versions for play and slick

### PR DESCRIPTION
**Pull request by Daxten**
Bumped slick / play versions, ran tests

### CODE REVIEW

**Comment by Daxten** [comment]
[info] Passed: Total 11, Failed 0, Errors 0, Passed 11
[error] (play-slick/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 76 s, completed Mar 2, 2017 12:20:41 PM

Test broken or commit?

**Comment by Daxten** [comment]
note: this is not compatible with the M version of slick, since some stuff in hikari got renamed

**Comment by marcospereira** [comment]
@Daxten thanks for this pull request.

The test is failing because the exception message expected by the assertion has changed. See this:

https://github.com/playframework/play-slick/commit/dde27f1c2f94b9f0d1c9b84eb91601ce141e618d#diff-ba4c9917aa8732326e6c4d10a9c77227L38

This line change is necessary at this pull request too.

**Comment by marcospereira** [comment]
Thank you, @Daxten.

**Pull request merged**
