### PR TITLE
#269 Slick evolutions with compile-time DI

### PR DESCRIPTION
**Pull request by iref**
I added `SlickEvolutionsTrait` and factory method for `DBApi` into evolutions plugin, so it'll possible to use slick-evolutions with compile-time dependency injection.

### CODE REVIEW

**Comment by dotta** [comment]
@iref Thanks a lot for your PR!

If I could cast my vote, I'd prefer to keep your commit https://github.com/iref/play-slick/commit/c2c93837d18f0377f2570316131fc6827ed336f7 + a factory method in `DbApiAdapter`. The reason is not that I think `DbApiAdapter` is a great name, but I also don't think that it actually generates any confusion here. Therefore, I'd prefer if we could keep the commit to its essence, i.e., enabling compile-time DI in play-slick-evolutions.

By the way, I know it's @jroper that suggested changing the name of the class (in #269). So, I guess I might be disagreeing with him more than you :-)

**Comment by dotta** [comment]
Also, it would be great if in your commit message you could add a `Fix #269`. Thanks!

**Comment by iref** [comment]
I added `Fix #269` to last commit message. You're right that `DBApiAdapter` doesn't create any confusion at the moment. So I don't have a problem with changing it back, although as library user I would prefer `SlickDBApi`.

**Comment by dotta** [comment]
`DBApiAdapter` is not part of the API, and it's definitely not a user facing type. In fact, it is declared private to the `evolutions` package, and it's located in the `evolutions.internal` package. Users should use `DbApi`.

I believe that adding 
```
trait SlickEvolutionsComponents {
  def api: SlickApi

  lazy val dbApi: DBApi = new DbApiAdapter(api)
 } 
```

plus the test you have already in this PR should be all it's needed to fix #269 (unless I'm overlooking something).

**Comment by iref** [comment]
That was my initial idea. @jroper noted in #269, that Play idea for DI is that everything can be manually created and wired and `DBApiAdapter` should either be public or expose factory method. 
That's reason why I moved `DBApiAdapter` from `evolutions.internal` to `evolution` package in iref/play-slick@7cfcc7ea2f906ab021edc71bbfe0bc23ebd60bfe . Implementation is still private, but it exposes factory method on companion object.

Granted that doesn't mean it has to be part of this pull request.
Hopefully I am not missing something although it definitely seems like it. :)

**Comment by dotta** [comment]
@iref Good point. Thanks!

How about the following
```
trait SlickEvolutionsComponents {
  def api: SlickApi

  lazy val dbApi: DBApi = SlickDBApi(api)
}

object SlickDBApi {
  def apply(api: SlickApi): DBApi = new DBApiAdapter(api)
}
```

This way we minimise changes, and also introduce a better name for the user facing API (i.e., `SlickDBApi`).

**Comment by iref** [comment]
This looks good to me. :)

I'll try to find time tonight and refactor it.

**Comment by dotta** [comment]
@iref Sounds good. Thanks for bearing with me :-) And I'm super thankful for your contribution!

P.S. Let me know if you happen to be at Scala Days in these days, as I'd love to meet. And, of course, beer is on me ;-)

**Comment by iref** [comment]
@dotta Thanks for quick feedback. :-)
Unfortunately, I'm not going to Scala Days this year. Hopefully, we'll meet at other conference soon. :)

**Comment by dotta** [comment]
Thank you!

Could you squash your commits? (Also, I think there should be no changes needed in `DBApiAdapter.scala`.)

Too bad you are not around for Scala Days, but hopefully we will have a chance to meet somewhere else soon!

**Comment by dotta** [comment]
@iref Thanks again!

**Comment by AmirKarimi** [comment]
We've implemented our `AppComponents` with `SlickEvolutionsComponents` like this:

```scala
trait AppComponents extends I18nComponents with BuiltInComponents with ControllerModuleV1 with SlickEvolutionsComponents {
  lazy val assets: Assets = wire[Assets]
  lazy val router: Router = wire[Routes] withPrefix "/"
  lazy val api: SlickApi = new DefaultSlickApi(environment, configuration, applicationLifecycle)
...
}
```

And load it in `ApplicationLoader`:

```scala

class MainApplicationLoader extends ApplicationLoader {
  def load(context: Context): Application = {
    Logger.configure(context.environment)
    loadAppComponents(context).application
  }

  def loadAppComponents(context: Context): AppComponents = {
    new BuiltInComponentsFromContext(context) with AppComponents
  }
}
```

And set the application loader in `application.conf`:
```
play.application.loader = com.myapp.backend.utils.MainApplicationLoader
```


But evolutions do not run! What did we miss? Are there any documentation about compile time DI configuration for evolutions?

**Comment by iref** [comment]
Your `AppComponents` trait need to extend `EvolutionsComponent` trait and evaluate `applicationEvolutions` eargerly on `AppComponents` creation.

**Pull request merged**
