### PR TITLE
Future/merge master

### PR DESCRIPTION
**Pull request by dotta**
This is a merge of master to the 1.1.x branch, plus one important commit that works around a Slick 3.1 regression (see https://github.com/playframework/play-slick/commit/d769056a47cf55014af94a1a35bcaa4f827d789f)

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @ms-tg,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Typesafe Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by dotta** [comment]
Sorry @ms-tg for the spam. I have no clue of why the @typesafehub-validator complained that you haven't signed the cla (while I know you actually have signed it).

**Comment by dotta** [comment]
This is ready to merge.

**Comment by dotta** [comment]
retest this please

**Comment by dotta** [comment]
Alright, I'll do the merge myself :-)

**Pull request merged**
