### PR TITLE
Issue/300 update codebase to slick 3 1

### PR DESCRIPTION
**Pull request by dotta**
**This PR expects that https://github.com/playframework/play-slick/pull/302 is merged first**

The only relevant commit in this PR is https://github.com/playframework/play-slick/commit/10405207f22393fdadcdd8e043024b58e3f30551

@nremond may be interested on this one ;-)

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @ms-tg,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Typesafe Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by dotta** [comment]
Failure is due to 

```
[info]   withConnection should
[error]     ! respect autocommit parameter
[error]      null (DBApiAdapter.scala:70)
[error] play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.withConnection(DBApiAdapter.scala:70)
[error] play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.withConnection(DBApiAdapter.scala:74)
[error] play.api.db.slick.evolutions.DBApiAdapterSpec$$anonfun$1$$anonfun$apply$22$$anonfun$apply$23.apply(DBApiAdapterSpec.scala:32)
[error] play.api.db.slick.evolutions.DBApiAdapterSpec$$anonfun$1$$anonfun$apply$22$$anonfun$apply$23.apply(DBApiAdapterSpec.scala:30)
[info] 
[error]     ! default autocommit to true
[error]      null (DBApiAdapter.scala:70)
[error] play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.withConnection(DBApiAdapter.scala:70)
[error] play.api.db.slick.evolutions.DBApiAdapterSpec$$anonfun$1$$anonfun$apply$22$$anonfun$apply$26.apply(DBApiAdapterSpec.scala:48)
[error] play.api.db.slick.evolutions.DBApiAdapterSpec$$anonfun$1$$anonfun$apply$22$$anonfun$apply$26.apply(DBApiAdapterSpec.scala:46)
```

I'll look into it on Monday.

**Comment by dotta** [comment]
Should be good now. Assuming the PR validator will succeed, this is up for review!

**Comment by dotta** [comment]
I believe the failure was spurious

```
[0m[[31merror[0m] [0m  [31m![0m return all records, which were enumerated in chunks[0m
[0m[[31merror[0m] [0m   Timeout after 1000ms of waiting for a connection. (BaseHikariPool.java:227)[0m
```

I thought this https://github.com/playframework/play-slick/commit/b682ab708eb4be992e3af78854f406c716fcbc6e would help working around the spurious failure, but it looks like it didn't.

**Comment by dotta** [comment]
The commit I linked in my previous comment (https://github.com/playframework/play-slick/commit/b682ab708eb4be992e3af78854f406c716fcbc6e) did seem to fix the spurious failures happening on the `iteratee-sample` project. In this PR, the `computer-database` sample project is failing rather similarly, so I'll try to apply the same workaround for all the sample projects.

By the way, there is a fairly long discussion about the same problem in https://github.com/brettwooldridge/HikariCP/issues/104, but it's not clear if there is indeed a bug on the hikaricp side, or connection are being leaked by the database connection library (in this case Slick).

**Pull request merged**
