### PR TITLE
Update to slick 3.2.1 -> propose play-slick plugin release of 2.1.1

### PR DESCRIPTION
**Pull request by jeffsteinmetz**
slick 3.2.1 fixes race-condition using unpinned/flatMapped DBIOActions, leading to missing decreaseInUseCount calls and possible stall of ManagedBlockingArrayQueue
https://github.com/slick/slick/issues/1730

### CODE REVIEW

**Comment by jeffsteinmetz** [comment]
note: did sign the CLA

**Comment by marcospereira** [comment]
Thank you, @jeffsteinmetz.

**Comment by jeffsteinmetz** [comment]
Great.  Is there a process / ETA to tag a 2.1.1 release, and push to the lightbend/typesafe repository?

**Comment by marcospereira** [comment]
@jeffsteinmetz already released. :-)

**Pull request merged**
