### PR TITLE
Upgrade Slick to 3.0.1

### PR DESCRIPTION
**Pull request by nremond**
Stefan Zeiger just released it : http://slick.typesafe.com/news/2015/08/06/slick-3.0.1-released.html

### CODE REVIEW

**Comment by dotta** [comment]
Thanks Nicolas!

**Comment by nremond** [comment]
Will you plan any `play-slick` release ?
Slick 3.0.1 contains fix that was blocking the use of `slick-pg`

**Comment by dotta** [comment]
Of course. We only need #292 to be merged, and then 1.0.1 will be out. So, if not tomorrow already, it will be early next week.

**Comment by nremond** [comment]
Awesome !

**Pull request merged**
