### PR TITLE
Update to slick 3.2.0-M1

### PR DESCRIPTION
**Pull request by stonexx**

### CODE REVIEW

**Comment by joost-de-vries** [comment]
Slick 3.2.0-M1 contains a fix for a [grave issue with potential deadlock on the transactionpool](https://github.com/slick/slick/pull/1461).
So I think this PR is an important upgrade for play-slick.

Pls consider merging this and creating a new version of play-slick.

**Comment by marcospereira** [comment]
Was this fixes ever backported to a stable release of Slick? This PR looks good to me, but since it depends on a milestone version, we would probably also release a milestone (or even a snapshot) version of play-slick.

What do you think?

**Comment by joost-de-vries** [comment]
Stefan Zeiger mentioned how the fix couldn't be back ported because of binary compatibility. I asked about the M1 moniker of the Slick version: according to him it's a stable production quality release. 
My understanding is there's no roadmap for a full 3.2 release. Personally I think this version should have been named 3.2.0 for that reason. But here we are.

**Comment by joost-de-vries** [comment]
@szeiger would this perhaps be a good reason to create a non-milestone release of Slick 3.2 ?

**Comment by joost-de-vries** [comment]
Is there a way that I can help with merging and releasing this PR?

**Comment by aganim-chariot** [comment]
The referenced slick deadlock issue is affecting my team as well.

**Comment by intracer** [comment]
Any chance here?

**Comment by joost-de-vries** [comment]
@stonexx care to add some explanation why you closed this PR?

**Comment by intracer** [comment]
Maybe because it's ignored since 29 Jul 2016?

**Comment by stonexx** [comment]
I do not use play-slick anymore. thx.

**Comment by joost-de-vries** [comment]
@stonexx I appreciate the sentiment. But I think you should relinquish your commit rights on play-slick if you don't care anymore.
@marcospereira @gmethvin I don't think that "I don't use play-slick anymore" is a valid reason to close this issue. Especially since it involves a potential critical production result of a deadlock in the connection pool of Slick.
So please reopen this issue.

**Comment by djx314** [comment]
Should it update to slick 3.2.0-M2 ?

**Comment by dcanfield40** [comment]
This _should_ be an update to M2.  Please, please, please merge/release this PR.  I'm hoping that "squeaky wheel gets the grease" at this point.....

**Comment by djx314** [comment]
@dcanfield40  I already use this pr and update to 3.2.0-M2. It works well. Just need to package to a jar and put it in to your project(lib folder).

**Comment by dcanfield40** [comment]
@djx314 That's great that 3.2.0-M2 appears to fix the transactional deadlock issue, but no one wants locally modified versions of this module and so this PR really needs to be merged....

**Comment by gmethvin** [comment]
play-slick 2.1.0-M1 is now released: https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-slick_2.11/2.1.0-M1/

**Comment by marcospereira** [comment]
While this release uses Slick 3.2.0-M1, you can easily update your projects to use 3.20-M2 since these versions are compatible.

Just update slick dependencies at your project:

```scala
libraryDependencies ++= "com.typesafe.slick" %% "slick" % "3.2.0-M2"

libraryDependencies ++= "com.typesafe.slick" %% "slick-hikaricp" % "3.2.0-M2"
```

**Comment by joost-de-vries** [comment]
That's a relief.
Tx guys!

**Comment by dcanfield40** [comment]
Thank you!

**Comment by djx314** [comment]
Great !

**Comment by szeiger** [comment]
Yes, we're working on it. 3.2 was held back by the uncertainty of whether
the deadlock bug is really fixed. I already created the new milestones, we
"only" need to triage the tickets and PRs.

**Comment by joost-de-vries** [comment]
Tx for the update @szeiger !

**Pull request merged**
