### PR TITLE
! dep upgrade slick version to 3.1.1

### PR DESCRIPTION
**Pull request by hepin1989**

### CODE REVIEW

**Comment by hepin1989** [comment]
target is master

**Comment by dotta** [comment]
@hepin1989 Thanks for your contribution! However, my thought is that we shouldn't merge it as 3.1.x Slick releases are binary compatible and hence users can just update the dependency in their build file. In fact, upgrading may cause trouble if you have another library that depends on Slick 3.1.0, since Slick trailing dot releases are not guaranteed to be forward binary compatible.

**Comment by dotta** [comment]
Closing this PR for the reasons I mentioned above, but I'm listening in case you don't agree (and it's easy to reopen the PR if you manage to convince me :-))

**Comment by hepin1989** [comment]
that's fine @dotta :).I will need add a slick dependency now,I just relay on `play-slick` thanks for that information.

**Comment by dotta** [comment]
I know that explicitly adding the dependency is (slightly) annoying. But it seems like a reasonable tradeoff :-)

**Pull request closed without merging**
