### PR TITLE
Sample app with compile time dependency injection

### PR DESCRIPTION
**Pull request by NicolaeNMV**
I adapted the di sample to use compile time dependency injection.

It includes the use of evolutions, test cases with in-memory database.

I struggled quite a bit to figure out how to make evolutions work with compile time DI. I think it can save other's people time.

### CODE REVIEW

**Comment by dotta** [comment]
@NicolaeNMV I'll try to review this early next week, but I wanted to thank you right away for this really nice and very needed contribution! If you have time, it would also be great to have a plug [in the documentation](https://github.com/playframework/play-slick/tree/master/docs).

**Comment by gmalouf** [comment]
Is this going to be merged?

**Comment by marcospereira** [comment]
@NicolaeNMV thanks for this contribution.

Unfortunately, this PR now has some conflicts and it is probably outdated with the recents changes. 

Could you please rebase with master?

Thank you!

**Comment by marcospereira** [comment]
Closing this since the PR is inactive. The contribution is still valuable, so, if someone want to submit an updated PR, it will very welcomed.

**Pull request closed without merging**
