### PR TITLE
Update versions of Play and Slick

### PR DESCRIPTION
**Pull request by marcospereira**

### CODE REVIEW

**Comment by richdougherty** [comment]
> Merging #412 into master will decrease coverage by 39.8%.

That's a bit hard to believe when you're just bumping version numbers!

**Comment by richdougherty** [comment]
LGTM

**Comment by marcospereira** [comment]
Yeah. I will probably disable that bot since it is not adding relevant information here. :-(

**Comment by marcospereira** [comment]
Backport to 3.0.x: 96eec4e

**Pull request merged**
