### PR TITLE
Migrate samples from play-slick repo to play-samples repo

### PR DESCRIPTION
**Pull request by Max-AR**
This PR removes the samples from this repo. See:

https://github.com/playframework/play-samples/pull/153

### CODE REVIEW

**Review by mkurz — APPROVED** [review]
👍

**Comment by mkurz** [comment]
@Mergifyio backport master

**Comment by mkurz** [comment]
Travis still tried to run tests for the removed samples, I pushed a commit to make that work, I hope you don't mind.

**Comment by Max-AR** [comment]
> Travis still tried to run tests for the removed samples, I pushed a commit to make that work, I hope you don't mind.

Thanks! Sorry I missed that one.

**Pull request merged**
