### PR TITLE
[5.2.x] Slick 3.5.0-RC1 + Scala 3 support 

### PR DESCRIPTION
**Pull request by mkurz**
Same as
- #805

TODO:
- [x] create 5.3.x branch, see commits

### CODE REVIEW

**Comment by nemoo** [comment]
If there is a play-slick  rc1 released that uses the latest slick rc1, I could test it in a production app.

**Comment by mkurz** [comment]
@nafg @nemoo Please try:
- [5.3.0-RC1](https://github.com/playframework/play-slick/releases/tag/5.3.0-RC1)
- [6.1.0-RC1](https://github.com/playframework/play-slick/releases/tag/6.1.0-RC1)

**Comment by nafg** [comment]
3.5.0 is finally released! Discussion thread: https://github.com/slick/slick/discussions/2908

**Comment by mkurz** [comment]
@nafg New play-slick release are out:
- https://github.com/playframework/play-slick/releases/tag/6.1.0
- https://github.com/playframework/play-slick/releases/tag/5.3.0

**Pull request merged**
