### PR TITLE
Bump Play version to 2.8.0-M2

### PR DESCRIPTION
**Pull request by renatocaval**

### CODE REVIEW

**Comment by dwijnand** [comment]
Update to sbt 1.2.8.

**Comment by ignasi35** [comment]
> Update to sbt 1.2.8.

It is [already using `1.2.8`](https://github.com/playframework/play-slick/blob/master/project/build.properties). 😅

**Comment by dwijnand** [comment]
No I misdiagnose the CI failure.  Restarted.

**Comment by ignasi35** [comment]
Failed again due to https://www.traviscistatus.com/incidents/mm020jn4nzcn

**Pull request merged**
