### PR TITLE
Added details on configuring without DATABASE_URL

### PR DESCRIPTION
**Pull request by jkutner**

### CODE REVIEW

**Comment by jkutner** [comment]
I added documentation for `DatabaseUrlDataSource` available in Slick 3.0.3

**Comment by dotta** [comment]
@jkutner Thanks for your contribution. Two comments:

1) It looks like the two commits could be merged, or am I missing something?
2) If `DatabaseUrlDataSource` is available only starting with Slick 3.0.3, it should be mentioned.

**Comment by jkutner** [comment]
@dotta done and done. thanks.

**Comment by dotta** [comment]
And thanks again!

**Pull request merged**
